# Generated by Django 4.0.5 on 2022-06-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/')),
                ('UserCity', models.CharField(blank=True, max_length=50, null=True)),
                ('UserState', models.CharField(blank=True, max_length=50, null=True)),
                ('UserPhone', models.CharField(blank=True, max_length=11, null=True)),
                ('UserAdress', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'AKTİF'), ('passive', 'PASİF')], default='active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
